services:
  higress:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:latest
    ports:
      - "8080:8080"
      - "8001:8001"
    restart: unless-stopped
  redis:
    image: docker.m.daocloud.io/library/redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
